Ali42Ibr/Woo-Woo-Network

Group Tasks/Weekly.md

Updated to include location of client email copy locaiton

---

Client Meetings/Week 3
Exploratory.md

Moved meeting agenda from exploratory file to Client meetings folder

Moved meeting template to folder

---

Client Meetings/Week 8
Client Meetings/Week 9

Notes taken during client meetings

Add meeting notes

---

Client Meetings/Week 8
front-the-unforgotten-ones-master/src/setupTests.js

adding changes to meeting and examples

---

Group Tasks/Nov_15-Nov_19.md

adding update week 11

---

woo-woo-backend-master/src/modules/admin/admin-page-controller.js
woo-woo-backend-master/src/modules/admin/admin-page-router.js
woo-woo-backend-master/src/router.js

healer list, profile, update, and user deleting functionality. Might reformat code using a helped file, and possibly add 'task manager' for admin user.

Admin page backend

---

woo-woo-backend-master/src/modules/admin/admin-page-controller.js
woo-woo-backend-master/src/modules/admin/admin-page-helper.js

Proper use of controller and helper.

Reformatted code

---

front-the-unforgotten-ones-master/src/components/home.jsx
woo-woo-backend-master/src/modules/public-healer-profile/public-healer-profile-controller.js

weird error with searchLocationUser array

some fixes

---

woo-woo-backend-master/src/modules/public-healer-profile/public-healer-profile-controller.js

API usually crashes once or twice per userlist, this is an attempt at correcting that

Keep trying API if it fails once..

---

Peer Testing Sessions/mohamad-testing/User-thinkaloud
Peer Testing Sessions/mohamad-testing/user-feedback

User feedback and think-aloud session notes

Peer-testing session notes

---

woo-woo-backend-master/src/modules/general/models/seeder/seed-data.js

Adding some extra tags

---

front-the-unforgotten-ones-master/src/components/home.jsx

Added new tag buttons to reflect new tags

Adding tag buttons to main page

---

front-the-unforgotten-ones-master/src/components/booking-page.jsx
woo-woo-backend-master/src/app.js
woo-woo-backend-master/src/modules/general/models/seeder/seed-data.js

fixing bogus service time values

---

Project Plan Presentation/info.md

project plan presentation

---

Group Tasks/Jan_31-Feb_4.md

 group tasks

---

front-the-unforgotten-ones-master/src/components/booking-page.jsx
front-the-unforgotten-ones-master/src/components/create-account.jsx
front-the-unforgotten-ones-master/src/components/home.jsx
woo-woo-backend-master/serviceAccountKey.json
woo-woo-backend-master/src/modules/appointment/controllers/appointment-booking-controller.js
woo-woo-backend-master/src/modules/auth/auth-helper/auth-helper.js
woo-woo-backend-master/src/modules/general/models/seeder/seed-data.js
woo-woo-backend-master/src/modules/general/utils/firebase/admin.js
woo-woo-backend-master/src/modules/general/utils/firebase/firebase.js
woo-woo-backend-master/src/modules/user/user-helper.js

Was able to fix firebase, users are now being added to database

Ali branch

---

front-the-unforgotten-ones-master/src/components/home.jsx
woo-woo-backend-master/db.bat
woo-woo-backend-master/src/app.js

tags still need to look better, almost good

tinkering with tags

---

Group Tasks/Feb_6-Feb_11.md

adding weekly updates

---

front-the-unforgotten-ones-master/src/components/home.jsx
woo-woo-backend-master/src/modules/public-healer-profile/public-healer-profile-controller.js
woo-woo-backend-master/weekWork.txt

small modification to person class

adding distance to person class

---

woo-woo-backend-master/src/modules/user/user-helper.js
woo-woo-backend-master/weekWork.txt

User can now signup and add location optionally

Finished user signup location addition

---

Client Meetings/week 20 

updating weekly logs

---

Client Meetings/week 22
front-the-unforgotten-ones-master/src/components/map.jsx

addding logs

---

Client Meetings/Week 23

adding logs

---

front-the-unforgotten-ones-master/src/components/schedule-page.jsx
front-the-unforgotten-ones-master/src/components/site-authorize.jsx
woo-woo-backend-master/src/modules/public-healer-profile/public-healer-profile-controller.js
woo-woo-backend-master/weekWork.txt

location works based on db location not hardcoded test values

final changes for real location system

---

Client Meetings/Week24
front-the-unforgotten-ones-master/src/components/nearme.jsx

 updating work logs

---

Client Meetings/Week 25 

adding weekly logs
